#!/bin/bash

sudo su
export installPath=$HOME/TGS
export functionPath=https://raw.githubusercontent.com/TheGuild-ops/TGS/main/tool/function
export installPathTool=https://raw.githubusercontent.com/TheGuild-ops/TGS/main/tool/install

mkdir $installPath
mkdir $installPath/source
mkdir $installPath/data
mkdir $installPath/bin

clear
rm start
if [ -s $installPath/data.json ]
then
echo -e "Welcome back $(cat $installPath/data.json | jq '.[0].name')\n How can i serve You?"
else
echo -e "Welcome to TheGuildScript-TGS-V1.0 Chosen One\
\nI must ask you some question\
\nWhat is your name? I will use this name as node name, if this will be necessary\nPls enter your name and press Enter"
read name
echo -e "Good work $name, do you want install firewall UFW for better secure?\n(Yes/No)"
while read response 
 do
  case $response in
  [yY][eE][sS]|[yY])
   curl $installPathTool/firewall | sudo bash
   ufwStatus=enable
   break
  ;;
  [dD][oO][nN][eE]|[dD])
   break
  ;;
  [nN][oO]|[nN])
   ufwStatus=disable
   break
  ;;
  *)
   echo "Please, enter Y(yes) or N(no)!"
  ;;
esac
done
echo $name
echo '[]' | jq '. +[{"name":"'$name'","ufwStatus":"'$ufwStatus'"}]' >  $installPath/data.json
curl https://raw.githubusercontent.com/TheGuild-ops/TGS/main/tool/init | bash
fi
clear
echo -e " Psl choose your action; \n 1 - install node; \n 2 - upgrade node \n"
read action

case "$action" in
  1 ) wget https://raw.githubusercontent.com/TheGuild-ops/tool/main/install/node && bash node;;
  2 ) echo "Цифра";;
  * ) echo "Ничего не выбрано";;
esac
